server.error.include-stacktrace=always
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.datasource.url=${DATA_SOURCE_PASAPALABRA}
spring.datasource.username=${DB_USER_PASAPALABRA}
spring.datasource.password=${DB_PASSWORD_PASAPALABRA}
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG
#spring.profiles.active=mysql
spring.profiles.active=sqlite